# -*- coding: utf-8 -*-
from . import nomenclator_mixin
from . import nationality
from . import profession
from . import specialty
from . import teaching_level
from . import teaching_category
from . import study_center
from . import document_required
from . import procedure_type
from . import detention_cause
from . import labour_sector
from . import normative
from . import structure
from . import who_enrolls
from . import terms_conditions
from . import res_city_inherit
from . import res_country_inherit
from . import res_country_state_inherit
from . import res_organism
from . import res_company_inherit
